# Generated by Django 4.2.16 on 2024-10-22 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='posts.post'),
        ),
    ]
